function map_phases_lines = taupLine()

% YF containers.Map 2024/05/05

	phase_list={ ...
		'P', ...
		'Pdiff', ...
		'PP', ...
		'PPP', ...
		'PcP', ...
		'PcS', ...
		'ScS', ...
		'ScP', ...
		'PS', ...
		'SP', ...
		'S', ...
		'Sdiff', ...
		'SS', ...
		'SKP', ...
		'PKS', ...
		'PKKS', ...
		'SKS', ...
		'SKKS', ...
		'SKiKS', ...
		'sSKS', ...
		'pSKS', ...
	};
	
	line_list = { ...
		'-', ...  % GMT navyblue
		'-', ...
		'-', ...
		'-', ...
		'-', ...  % GMT deepskyblue
		'-', ...
		'-', ...  % GMT cyan
		'--', ...
		'--', ...
		'--', ...
		'-', ...  % GMT blue
		'--', ...
		':', ...
		':', ...
		'-', ...  % GMT yellow2
		'-', ...  % GMT purple
		'-', ...  % GMT red3
		'-', ...  % GMT darkorange2
		':', ...
		':', ...
		'-.', ...
	};

	map_phases_lines = containers.Map(phase_list,line_list);
