function map_phases_colors = taupColor()

% YF containers.Map 2024/05/05

	phase_list={ ...
		'P', ...
		'Pdiff', ...
		'PP', ...
		'PPP', ...
		'PcP', ...
		'PcS', ...
		'ScS', ...
		'ScP', ...
		'PS', ...
		'SP', ...
		'S', ...
		'Sdiff', ...
		'SS', ...
		'SKP', ...
		'PKS', ...
		'PKKS', ...
		'SKS', ...
		'SKKS', ...
		'SKiKS', ...
		'sSKS', ...
		'pSKS', ...
	};
	
	color_list = { ...
		[0 0 128]/255, ... % GMT navyblue
		'r', ...
		'g', ...
		'k', ...
		[0 191 255]/255, ... % GMT deepskyblue
		'm', ...
		[0 255 255]/255, ...  % GMT cyan
		'r', ...
		'g', ...
		'k', ...
		[0 0 255]/255, ...  % GMT blue
		'm', ...
		'r', ...
		'g', ...
		[238 238 0]/255, ...  % GMT yellow2
		[160 32 240]/255, ...  % GMT purple
		[205 0 0]/255, ...  % GMT red3
		[238 118 0]/255, ...  % GMT darkorange2
		'k', ...
		'm', ...
		'r' ...
	};

	map_phases_colors = containers.Map(phase_list,color_list);
